name: Bun-testflow
on: [push]

jobs:
  Bun-setup:
    name: Set up Bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: echo "Running all Bun tests"
      - run: bun install

  Bun-test:
    name: Run Bun tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun test
